# Generated by Django 5.2 on 2025-04-15 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_disciplina_feedback_delete_contato_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-id'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='feedback',
        ),
        migrations.AddField(
            model_name='feedback',
            name='disciplina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedback.disciplina', verbose_name='Disciplina'),
        ),
    ]
